### ISSUE TITLE
Start/Stop Information

### ISSUE THREAD

**Issue by ProtectorGamer** [jindalpriyanshu101/RecorderX#4]
Hello There, I would like to suggest some basic add-ons for RecorderX.

Whenever we start/stop recording. There is no Information whether the recording has been started & when we stopped it. I think it should be Improved and a pop-up message regarding this should be added whenever we start/stop recording anything.

Also, Make 2 versions in which 1st is for limited resolution whereas 2nd one is for full resolution.

I hope my suggestion will be taken into consideration.

**Comment by jindalpriyanshu101** [comment]
Hi, thanks for highlighting this issue. Although its already made sure that the "Recording Started" Text get updated on the GUI window maybe its not yet noticeable, will fix it.
- A windows pop-up notification will be added with the next patch. (Feel free to suggest a better alternative if you have any)

> Also, Make 2 versions in which 1st is for limited resolution whereas 2nd one is for full resolution.

Not sure what you exactly meant here? can you please share more details?
